mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant_menu.urls')) # the urls file under restaraunt_menu folder
]

restaurant_menu/urls.py
# link urls to view

from django.urls import path
from . import views

urlpatterns = [
    path('', views.MenuList.as_view(), name='home'),
    path('item/<int:pk>/', views.MenuItemDescription.as_view(), name="menu_item") # int primary key pk for each item id, for dynamic urls
]

restaurant_menu/models.py
from django.db import models
from django.contrib.auth.models import User

MEAL_CATEGORY = (
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("entree", "Entree"),
    ("desserts", "Desserts")
)

STATUS = (
    (0, "Unavailable"),
    (1, "Available")
)

# Create your models here.
class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    desc = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    meal_category = models.CharField(max_length=200, choices=MEAL_CATEGORY)
    author = models.ForeignKey(User, on_delete=models.PROTECT) # author can be deleted from db but not their meal 
    status = models.IntegerField(choices=STATUS, default=1)
    date_created = models.DateTimeField(auto_now_add=True) # records whenever item is added
    date_updated = models.DateTimeField(auto_now=True) # records whenever item is edited

    # returns obj in str format
    def __str__(self):
        return self.meal

restaurant_menu/views.py
from typing import Any
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_CATEGORY

# Create your views here.
class MenuList(generic.ListView):
    queryset = Item.objects.order_by("date_created") # connect Item model to menu list view
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # make context dictionary instad of empty one
        context["meals"] = MEAL_CATEGORY
        return context

class MenuItemDescription(generic.DetailView):
    # model is predefined var name
    model = Item
    template_name = "menu_item_detail.html"

restaurant_menu/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charsest="UTF-8" />
    <title></title>
  </head>
  <body>
    <h1 id="menu-title">Menu</h1>

    <!--comes from views.py, get the uppercase meal category-->
    {% for meal in meals %}
    <h2>{{ meal.1 }}</h2>
    {% for row in item_list %}
    <!-- item_list is special var name for the list of db record Item-->
    {% if row.meal_category == meal.0 %} {% if row.status == 0 %}
    <a class="unavailable-meal" href="{% url 'menu_item' row.pk %}"
      ><h3><del>{{ row.meal }}</del></h3>
    </a>
    <p>{{ row.desc }}</p>
    {% else %}
    <a class="available-meal" href="{% url 'menu_item' row.pk %}"
      ><h3>{{ row.meal }}</h3></a
    >
    <p>{{ row.desc }}</p>
    {% endif %}
    <!-- inner if block-->
    {% endif %}
    <!--inner if block-->
    {% endfor %}
    <!--inner for loop-->
    {% endfor %}
    <!--outer for loop-->
  </body>
</html>

restaurant_menu/templates/menu_item_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charsest="UTF-8" />
    <title></title>
  </head>
  <body>
    <h1 id="item-name">{{ item.meal }}</h1>
    <p id="item-description">{{ item.desc }}</p>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charsest="UTF-8" />
    <title></title>
  </head>
  <body>
    <h1>Menu</h1>
  </body>
</html>